### PR TITLE
Save endpoint view and test

### PR DESCRIPTION
**Pull request by zzacharo**

### CODE REVIEW

**Comment by egabancho** [comment]
Hey! Have you considered what I told you [a few days ago](https://github.com/inveniosoftware-contrib/invenio-record-editor/pull/4#issuecomment-254184616) about reusing [invenio-records-rest](https://github.com/inveniosoftware/invenio-records-rest)?

I think it would be nice if you could take a look at it because you get most of the things you are doing (and not doing like access rights) for free.

cc @kaplun

**Comment by kaplun** [comment]
cc: @jmartinm

**Comment by zzacharo** [comment]
@egabancho I will check them today! I just started with something working using invenio-packages in general. I will take a look now!

**Comment by jmartinm** [comment]
@egabancho I agree that it would be nice to reuse as many parts of Invenio as possible, although I am not sure if directly using `invenio-records-rest` would be flexible enough as a backend for a record editor.

Let's say, for the `save` functionality in this PR, I guess the equivalent would be to call the [patch](https://github.com/inveniosoftware/invenio-records-rest/blob/master/invenio_records_rest/views.py#L623) method of `invenio-records-rest`. If am correct this method can only be called through http directly from the JS of the editor. So if we want to capture the `validation` errors and return a editor-friendly data structure we would have to modify such a function.

So what you mean is to reuse the helpers available in `invenio-records-rest` (similar to what deposit does? https://github.com/inveniosoftware/invenio-deposit/blob/master/invenio_deposit/views/rest.py#L38-L43 ) rather than directly using `invenio-records-rest` ? In which case I agree it can be a good idea to help fetching the record, permissions and so on.

**Comment by jmartinm** [comment]
Closing this since it is now outdated.

**Pull request closed without merging**
